
<div class="row">
    <div class="col">
        <form enctype="multipart/form-data" name="addData" method="post" id="addData" class="form" action="<?php echo $block->getFormAction(); ?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span>Feedback Form</span></legend>
                <fieldset class="fieldset row">
                    <div class="fields">
                        <div class="field name required">
                            <label class="label" for="title"><span>Title</span></label>
                            <div class="control">
                                <input name="title" id="Title" title="Title" value="" class="input-text" type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label" for="content"><span>Message</span></label>
                            <div class="control">
                                <textarea name="message" id="message" rows="5" cols="8" class="input-text" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="content"><span>Image</span></label>
                            <div class="upload-wrapper" data-bind="scope: 'uploader'">
                                <!-- ko template: getTemplate() --><!-- /ko -->
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span>Save</span></button>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
{
   ".upload-wrapper": {
       "Magento_Ui/js/core/app": {
           "components": {
               "uploader": {
                   "component":"Magento_Ui/js/form/element/image-uploader",
                   "template":"Overdose_Testimonials/image",
                   "previewTmpl":"Overdose_Testimonials/preview",
                   "allowedExtensions": "jpg jpeg gif png",
                   "maxFileSize": "1048576",
                   "dataScope":"imageupload",
                   "uploaderConfig": {
                        "url": "<?php echo $block->getUrl('feedback/index/uploadimage'); ?>"
                   }
               }
           }
       }
   }
}

</script>
